
name: Staging
on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      API_DOMAIN: https://7oquizbc8g.execute-api.ap-southeast-1.amazonaws.com/staging/
      CDN_DOMAIN: https://d2ecox8kjhkvbt.cloudfront.net/uploads/
      PLATFORM: android
      PREFIX: kkp
      ENVIRONMENT: STG
  
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: npm
      - run: npm config set registry http://registry.npmjs.org/
      - run: npm install --production=true
      - run: echo "APP_ENV_PROJECT=Leni2022" >> .env
      - run: echo "APP_ENV_PLATFORM=$PLATFORM" >> .env
      - run: echo "APP_ENV_PREFIX=$PREFIX" >> .env
      - run: echo "APP_ENV_PUBLIC_PATH=" >> .env
      - run: echo "APP_ENV_BUILD_NO=1.8.${{ github.run_number }}" >> .env
      - run: echo "APP_ENV_COOKIE_TIME_LIMIT=14" >> .env
      - run: echo "APP_ENV_API_DOMAIN=$API_DOMAIN" >> .env
      - run: echo "APP_ENV_CDN_DOMAIN=$CDN_DOMAIN" >> .env
      - run: echo "APP_ENV_ENVIRONMENT=$ENVIRONMENT" >> .env
      - run: echo "APP_ENV_STAGE=$CI_COMMIT_REF_NAME" >> .env
      - run: cat .env
      - run: npm install
      - run: rm -rf build
      - run: npm run build:android
      - run: npm run build:ios
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-southeast-1
      - run: aws s3 sync ./build s3://${{ secrets.STG_BUCKET }} --acl public-read-write
      
      - name: Update App Version
        run: |
          curl --request GET \
          --header 'admin-key: ${{ secrets.STG_ADMIN_KEY }}' \
          --header 'content-type: application/json' \
          --url $API_DOMAIN/admin/appVersion/1.8.${{ github.run_number }}
      
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.STG_DISTRIBUTION }}
          PATHS: "/android/index.html /android/assets/* /ios/index.html /ios/assets/* /uploads/appConfig.json /uploads/appHomeConfig.json"
          AWS_REGION: "ap-southeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}

